### ISSUE TITLE
Xiaomi 14 Ultra 1.0.15.0 translation error

### ISSUE THREAD

**Issue by hubert-rutkowski** [kacskrz/xiaomi.eu_PL_HyperOS1.0#1]
In the camera settings in the latest system version for the Xiaomi 14 Ultra, there is a new setting that is not translated for Polish.

![Screenshot_2024-07-01-17-43-39-326_com android camera](https://github.com/kacskrz/xiaomi.eu_PL_HyperOS1.0/assets/90204209/9a450005-9c6f-45d5-956c-f62ddc00f67d)

**Comment by kacskrz** [comment]
Added in this commit, looks like a few hours later than our build released: https://github.com/kacskrz/xiaomi.eu_PL_HyperOS1.0/commit/8040f242e50ca5c885d41fd301e97b83d23e7f00

So, it will be there in next build :)
